[build]
functions = "netlify/functions"
publish = "dist"
command = "npx vite build"

[functions]
node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200